name: Generate Wiki from XML Comments

on:
  push:
    branches: [main]
    paths:
      - 'SaveFramework/**/*.cs'
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:

        
  generate-wiki:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Generate Wiki Documentation
        run: |
          chmod +x .github/scripts/generate-wiki.sh
          ./.github/scripts/generate-wiki.sh

      - name: Update Wiki
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bash .github/scripts/update-wiki.sh

