name: Release on tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 将 UPM 结构拷贝为 Assets/Plugins/SaveFramework，用于打 unitypackage（无需 Unity 许可）
      - name: Prepare Assets layout for unitypackage
        shell: bash
        run: |
          set -eux
          mkdir -p "Assets/Plugins/SaveFramework"
          if [ -d Runtime ]; then
            rsync -av Runtime/ "Assets/Plugins/SaveFramework/Runtime/"
          fi
          if [ -d Editor ]; then
            rsync -av Editor/ "Assets/Plugins/SaveFramework/Editor/"
          fi
          if [ -d Generated ]; then
            rsync -av Generated/ "Assets/Plugins/SaveFramework/Generated/"
          fi

      # 生成 .unitypackage（要求文件具备 .meta）
      - name: Create .unitypackage
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          package-path: Assets/Plugins/SaveFramework
          project-folder: .
          include-files: Assets/Plugins/SaveFramework/**/*
      - name: Rename unitypackage with tag
        shell: bash
        run: |
          set -eux
          FILE=$(ls -1 *.unitypackage | head -n 1)
          mv "$FILE" "SaveFramework-${{ github.ref_name }}.unitypackage"

      # 打一个 UPM 结构的 zip（便于离线导入/镜像）
      - name: Create UPM zip
        shell: bash
        run: |
          set -eux
          ZIP="SaveFramework-UPM-${{ github.ref_name }}.zip"
          files=(package.json README.md README_EN.md QUICKREF.md CHANGELOG.md)
          dirs=()
          [ -d Runtime ] && dirs+=(Runtime)
          [ -d Editor ] && dirs+=(Editor)
          [ -d Sample ] && dirs+=(Sample)
          if [ ${#dirs[@]} -eq 0 ]; then
            echo "No UPM content dirs found, skipping zip"
          else
            zip -r "$ZIP" "${files[@]}" "${dirs[@]}" 2>/dev/null || true
          fi

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: SaveFramework ${{ github.ref_name }}
          body: |
            Automated release for tag ${{ github.ref_name }}.

            Assets:
            - SaveFramework-${{ github.ref_name }}.unitypackage (Assets/Plugins layout)
            - SaveFramework-UPM-${{ github.ref_name }}.zip (UPM package)
          files: |
            SaveFramework-${{ github.ref_name }}.unitypackage
            SaveFramework-UPM-${{ github.ref_name }}.zip
